export enum InpJunction {
  Name = "Name",
  Description = "Description",
  Tag = "Tag",
  Invert_Elev = "Invert Elev",
  Depth = "Depth",
  Initial_Depth = "Initial Depth",
  Surcharge_Depth = "Surcharge Depth",
  Ponded_Area = "Ponded Area",
  Baseline = "Baseline",
  Basline_Pattern = "Basline Pattern",
  Time_Series = "Time Series",
  Scale_Factor = "Scale Factor",
  Average_Value = "Average Value",
  Time_Pattern1 = "Time Pattern1",
  Time_Pattern2 = "Time Pattern2",
  Time_Pattern3 = "Time Pattern3",
  Time_Pattern4 = "Time Pattern4",
  Hydrograph = "Hydrograph",
  Sewered_Area = "Sewered Area",
  Rim_Elev = "Rim Elev",
}

export enum InpOutfall {
  Name = "Name",
  Description = "Description",
  Tag = "Tag",
  Invert_Elev = "Invert Elev",
  Tide_Gate = "Tide Gate",
  Type = "Type",
  Fixed_Stage = "Fixed Stage",
  Curve_Name = "Curve Name",
  Series_Name = "Series Name",
  Baseline = "Baseline",
  Baseline_Pattern = "Baseline Pattern",
  Time_Series = "Time Series",
  Scale_Factor = "Scale Factor",
  Average_Value = "Average Value",
  Time_Pattern1 = "Time Pattern1",
  Time_Pattern2 = "Time Pattern2",
  Time_Pattern3 = "Time Pattern3",
  Time_Pattern4 = "Time Pattern4",
  Hydrograph = "Hydrograph",
  Sewershed_Area = "Sewershed Area",
  Rim_Elev = "Rim Elev",
}

export enum InpConduit {
  Name = "Name",
  Inlet_Node = "Inlet Node",
  Outlet_Node = "Outlet Node",
  Description = "Description",
  Tag = "Tag",
  Length = "Length",
  Roughness = "Roughness",
  Inlet_Offset = "Inlet Offset",
  Outlet_Offset = "Outlet Offset",
  Initial_Flow = "Initial Flow",
  Flow_Limit = "Flow Limit",
  Entry_Loss_Coeff = "Entry Loss Coeff.",
  Exit_Loss_Coeff = "Exit Loss Coeff",
  Avg_Loss_Coeff = "Avg Loss Coeff",
  Flap_Gate = "Flap Gate",
  Cross_Section = "Cross Section",
  Geom1 = "Geom1",
  Geom2 = "Geom2",
  Geom3 = "Geom3",
  Geom4 = "Geom4",
  arrels = "Barrels",
  Transect = "Transect",
  Shape_Curve = "Shape Curve",
  Culvert_Code = "Culvert Code",
  Slope = "Slope",
}
